services:
  drupal-quickstart-app:
    image: drupal:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./app:/opt/drupal
      - ./scripts/php-memory-limit.ini:/usr/local/etc/php/conf.d/php-memory-limit.ini
    working_dir: /opt/drupal
    depends_on:
      - drupal-quickstart-db
  drupal-quickstart-db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - drupal-quickstart-db:/var/lib/mysql
volumes:
  drupal-quickstart-db:
